### ISSUE TITLE
Can't get the program to work

### ISSUE THREAD

**Issue by pre63** [erpuno/ws#4]
When testing with [websocat](https://github.com/vi/websocat) the request fails.

```
~/o/supreme [1] $ websocat ws://0.0.0.0:5000/echo
websocat: WebSocket response error: Sec-WebSocket-Accept is invalid
websocat: error running
```

It works when I set custom heather, which changes the order of the request headers, I don't know if that's relevant.
```
~/o/supreme $ websocat ws://0.0.0.0:5000/echo -H='sec-websocket-key: CHBsjysDVjJ77jY4A'
TICK
TICK
TICK
TICK
```

I can't get the example to the program to work with any other WebSocket client.

**Comment by rzrn** [comment]
>…which changes the order of the request headers, I don't know if that's relevant.

It shouldn’t. It’s easy to see that headers in both cases are read correctly by simply inserting “printfn” here: https://github.com/erpuno/ws/blob/master/src/6455.fs#L30.

>…any other WebSocket client.

Which? At least, it should work correctly with [wscat](https://github.com/websockets/wscat).

**Comment by pre63** [comment]
Thanks for the quick reply.

So it works with wscat. And I'm not sure why but not with [websocat](https://github.com/vi/websocat), the [flutter client](https://flutter.dev/docs/cookbook/networking/web-sockets), [websocket-client](https://apps.apple.com/us/app/websocket-client/id1399498094?mt=12).

All the other clients work with `websocat -s 8888`.


**Test case: client websocat**
 👎 
It fails when trying to connect.
```
~/o/ws (master|✚2) [1] $ websocat ws://0.0.0.0:1900/echo
websocat: WebSocket response error: Sec-WebSocket-Accept is invalid
websocat: error running
```
Wireshark capture
![image](https://user-images.githubusercontent.com/1747271/113486874-b8553180-9469-11eb-8e6f-6c0e019b3998.png)
![image](https://user-images.githubusercontent.com/1747271/113486889-cc992e80-9469-11eb-85f8-7b98eb54b13e.png)

**Test case: client websocat with custom header**
  👍 
```
~/o/ws (master|✚2) [1] $ websocat ws://0.0.0.0:1900/echo -H='Sec-WebSocket-Key: CHBsjysDVjJ77jY4A'
hello
hello
TICK
TICK
^C⏎     
```
Wireshark capture
![image](https://user-images.githubusercontent.com/1747271/113486947-0c601600-946a-11eb-9e4d-83239a7d8142.png)
![image](https://user-images.githubusercontent.com/1747271/113486954-18e46e80-946a-11eb-8430-1b2ddf053155.png)

**Test case: client wscat**
👍
```
~/o/ws (master|✚2) $ wscat --connect ws://0.0.0.0:1900/echo
Connected (press CTRL+C to quit)
< TICK
> hello
< hello
< TICK
> ⏎    
```
Wireshark capture
![image](https://user-images.githubusercontent.com/1747271/113487021-7d9fc900-946a-11eb-9acc-8737e5feae6d.png)
![image](https://user-images.githubusercontent.com/1747271/113487027-885a5e00-946a-11eb-9b3c-1c9a7887a0b9.png)

**Test case: Flutter WebSocket Client**
👎 
It Fails to connect. The server never responds with HTTP 101.
```
IOWebSocketChannel.connect('ws://0.0.0.0:1900/echo')
```
![image](https://user-images.githubusercontent.com/1747271/113487114-f7d04d80-946a-11eb-8b5e-3221f4d4b517.png)


**Test case: Flutter WebSocket Client using the websocat server**
👍 
Server
```
websocat -s 8888
```
Client
```
IOWebSocketChannel.connect('ws://0.0.0.0:8888/')
```
Wireshark capture
![image](https://user-images.githubusercontent.com/1747271/113487172-68776a00-946b-11eb-8551-d38734f2dd2c.png)
![image](https://user-images.githubusercontent.com/1747271/113487183-7d53fd80-946b-11eb-8d1f-9d0688ce7991.png)


Ultimately I'm looking to make it work with flutter.
